### ISSUE TITLE
Volume calculation should respect interpretation type

### ISSUE THREAD

**Issue by TobiasRosskopf** [bluemodel/BlueM.Wave#112]
The volume of a time series is calculated in the function below:

https://github.com/bluemodel/BlueM.Wave/blob/037010d9aea669d614f9bfdf5eff9f175948d54c/source/Classes/TimeSeries.vb#L402-L429

But this will always calculate the volume with **linear interpretation**. If it's a time series with block interpretation the volume of its should be calculated **blockwise**.

Additionally the volume is just calculateted if the unit of the time series matches **"/s"**.  It may be usefull to recognize "/min", "/h", "/d" as well.

**Instantenious (linear) interpretation**
![instantenious](https://github.com/bluemodel/BlueM.Wave/assets/42942019/b3379342-30db-4464-84fb-a8b31d5f32f1)

**Block Interpretation**
![blockright](https://github.com/bluemodel/BlueM.Wave/assets/42942019/72844e6e-522e-4f6f-9e98-ca2de80dcf1f)

**Comment by jamaa** [comment]
there are some tricky situations:
* if the interpretation is blockright, we have to ignore the last node, because we do not know the timespan for which it is valid (we cannot assume that the time series is equidistant)
* same thing with blockleft and the first node
* if the interpretation is CumulativePerTimestep, units per time unit such as mm/d don't really make sense because by definition each node's value is already the sum (volume) between the last node and the current one
* we actually need to consider NaN nodes. In the old implementation, NaN-nodes were simply filtered out but that is not correct.

**Comment by jamaa** [comment]
I am a bit unsure about the following:
For interpretations such as CumulativePerTimestep and Cumulative, I am implementing that the volume will be NaN. Theoretically we could also return the sum and the last value, respectively, as the volume, but I think that would cause more confusion than be helpful?

**Comment by jamaa** [comment]
For reference, the new implementation is as follows (see also [wiki](https://wiki.bluemodel.org/index.php/BlueM.Wave#Volume_property)):
>Wave calculates and displays the Volume property of a time series (e.g. for [GoodnessOfFit](https://wiki.bluemodel.org/index.php/Wave:GoodnessOfFit) analysis or in the properties window), if a time series' unit ends with "/s", "/min", "/h" or "/d" (e.g. "m³/s", "mm/h", etc.) and its interpretation is either Instantaneous, BlockLeft or BlockRight, by integrating the values over time while respecting the interpretation. Time series with other units or interpretations only have the Sum property. NaN nodes cause the adjacent timesteps to not contribute to the volume (depends on the interpretation).

Additional technical details:
* When the interpretation is BlockRight, the last node does not contribute to the volume because it doesn't have a defined end of timestep
* The same applies for interpretaion BlockLeft and the first node (no defined start of timestep)
* An NaN node causes adjacent timesteps to not contribute to volume, depending on the interpretation:
  * Instantaneous: both timesteps left and right of the NaN node do not contribute
  * BlockLeft: timestep to the right of the NaN node does not contribute
  * BlockRight: timestep to the left of the NaN node does not contribute
